// <auto-generated>
// This file was generated from tablet-v2.xml
// Stability: Stable
// Link: https://wayland.app/protocols/tablet-v2
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.Stable;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// zwp_tablet_manager_v2
/// <para> controller object for graphic tablet devices </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/tablet-v2/#zwp_tablet_manager_v2</see>
/// </summary>
public sealed partial class ZwpTabletManagerV2 : WaylandObject, IWaylandObjectFactory<ZwpTabletManagerV2>
{
    public const string InterfaceName = "zwp_tablet_manager_v2";
    public static string _StaticInterfaceName => "zwp_tablet_manager_v2";
    public const int InterfaceVersion = 2;

    public ZwpTabletManagerV2(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>
    /// Get the tablet seat
    /// <para>
    /// <br/>
    /// Get the zwp_tablet_seat_v2 object for the given seat. This object<br/>
    /// provides access to all graphics tablets in this seat.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe ZwpTabletSeatV2 GetTabletSeat(WlSeat seat)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.ZwpTabletSeatV2,
            (uint)WaylandInterfaces.ZwpTabletSeatV2->Version,
            0,
            (nint)args
        );

        return new ZwpTabletSeatV2(newProxy, Display);
    }

    /// <summary>
    /// Release the memory for the tablet manager object
    /// <para>
    /// <br/>
    /// Destroy the zwp_tablet_manager_v2 object. Objects created from this<br/>
    /// object are unaffected and should be destroyed separately.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static ZwpTabletManagerV2 Create(nint handle, WlDisplay display)
    {
        return new ZwpTabletManagerV2(handle, display);
    }
}
