// <auto-generated>
// This file was generated from river-window-management-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-window-management-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_decoration_v1
/// <para> a window decoration </para>
/// <para> Version: 3 </para>
/// <see>https://wayland.app/protocols/river-window-management-v1/#river_decoration_v1</see>
/// </summary>
public sealed partial class RiverDecorationV1 : WaylandObject, IWaylandObjectFactory<RiverDecorationV1>
{
    public const string InterfaceName = "river_decoration_v1";
    public static string _StaticInterfaceName => "river_decoration_v1";
    public const int InterfaceVersion = 3;


    #region GenerateConstructor

    public RiverDecorationV1(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateEnums

    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// failed to commit the surface before the window manager commit
        /// </summary>
        NoCommit = 0,
    }


    #endregion // GenerateEnums


    #region GenerateRequests

    /// <summary>
    /// Destroy the decoration object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the decoration<br/>
    /// object and that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set offset from the window's top left corner
    /// <para>
    /// <br/>
    /// This request sets the offset of the decoration surface from the top left<br/>
    /// corner of the window.<br/>
    /// <br/>
    /// If this request is never sent, the x and y offsets are undefined by this<br/>
    /// protocol and left up to the compositor.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetOffset(int x, int y)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].i = x;
        args[1].i = y;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Sync next commit with other rendering state
    /// <para>
    /// <br/>
    /// Synchronize application of the next wl_surface.commit request on the<br/>
    /// decoration surface with rest of the state atomically applied with the<br/>
    /// next river_window_manager_v1.render_finish request.<br/>
    /// <br/>
    /// The client must make a wl_surface.commit request on the decoration<br/>
    /// surface after this request and before the render_finish request, failure<br/>
    /// to do so is a protocol error.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SyncNextCommit()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }


    #endregion // GenerateRequests

    public static RiverDecorationV1 Create(nint handle, WlDisplay display)
    {
        return new RiverDecorationV1(handle, display);
    }
}
