// <auto-generated>
// This file was generated from river-window-management-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-window-management-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_node_v1
/// <para> a node in the render list </para>
/// <para> Version: 3 </para>
/// <see>https://wayland.app/protocols/river-window-management-v1/#river_node_v1</see>
/// </summary>
public sealed partial class RiverNodeV1 : WaylandObject, IWaylandObjectFactory<RiverNodeV1>
{
    public const string InterfaceName = "river_node_v1";
    public static string _StaticInterfaceName => "river_node_v1";
    public const int InterfaceVersion = 3;

    public RiverNodeV1(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>
    /// Destroy the decoration object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the node<br/>
    /// object and that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set absolute position of the node
    /// <para>
    /// <br/>
    /// Set the absolute position of the node in the compositor's logical<br/>
    /// coordinate space. The x and y coordinates may be positive or negative.<br/>
    /// <br/>
    /// Note that the position of a river_window_v1 refers to the position of<br/>
    /// the window content and is unaffected by the presence of borders or<br/>
    /// decoration surfaces.<br/>
    /// <br/>
    /// If this request is never sent, the position of the node is undefined by<br/>
    /// this protocol and left up to the compositor.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetPosition(int x, int y)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].i = x;
        args[1].i = y;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node above all other nodes
    /// <para>
    /// <br/>
    /// This request places the node above all other nodes in the compositor's<br/>
    /// render list.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceTop()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node below all other nodes
    /// <para>
    /// <br/>
    /// This request places the node below all other nodes in the compositor's<br/>
    /// render list.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceBottom()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 3;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node above another node
    /// <para>
    /// <br/>
    /// This request places the node directly above another node in the<br/>
    /// compositor's render list.<br/>
    /// <br/>
    /// Attempting to place a node above itself has no effect.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceAbove(RiverNodeV1 other)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(other?.Handle ?? IntPtr.Zero);

        const uint opcode = 4;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Place node below another node
    /// <para>
    /// <br/>
    /// This request places the node directly below another node in the<br/>
    /// compositor's render list.<br/>
    /// <br/>
    /// Attempting to place a node below itself has no effect.<br/>
    /// <br/>
    /// This request modifies rendering state and may only be made as part of a<br/>
    /// render sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void PlaceBelow(RiverNodeV1 other)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(other?.Handle ?? IntPtr.Zero);

        const uint opcode = 5;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static RiverNodeV1 Create(nint handle, WlDisplay display)
    {
        return new RiverNodeV1(handle, display);
    }
}
