namespace WaylandDotnet.Internal;

// <auto-generated>
// This file was generated from river-window-management-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-window-management-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

/// <summary> Static Wayland interface definitions </summary>
public static unsafe partial class WaylandInterfaces
{
    // Use lazy initialization to ensure Core interfaces are initialized first
    private static WlInterface* _riverwindowmanagerv1;
    private static WlInterface* _riverwindowv1;
    private static WlInterface* _riverdecorationv1;
    private static WlInterface* _rivershellsurfacev1;
    private static WlInterface* _rivernodev1;
    private static WlInterface* _riveroutputv1;
    private static WlInterface* _riverseatv1;
    private static WlInterface* _riverpointerbindingv1;

    public static WlInterface* RiverWindowManagerV1
    {
        get
        {
            if (_riverwindowmanagerv1 == null)
            {
                _riverwindowmanagerv1 = CreateRiverWindowManagerV1Interface();
            }
            return _riverwindowmanagerv1;
        }
    }
    public static WlInterface* RiverWindowV1
    {
        get
        {
            if (_riverwindowv1 == null)
            {
                _riverwindowv1 = CreateRiverWindowV1Interface();
            }
            return _riverwindowv1;
        }
    }
    public static WlInterface* RiverDecorationV1
    {
        get
        {
            if (_riverdecorationv1 == null)
            {
                _riverdecorationv1 = CreateRiverDecorationV1Interface();
            }
            return _riverdecorationv1;
        }
    }
    public static WlInterface* RiverShellSurfaceV1
    {
        get
        {
            if (_rivershellsurfacev1 == null)
            {
                _rivershellsurfacev1 = CreateRiverShellSurfaceV1Interface();
            }
            return _rivershellsurfacev1;
        }
    }
    public static WlInterface* RiverNodeV1
    {
        get
        {
            if (_rivernodev1 == null)
            {
                _rivernodev1 = CreateRiverNodeV1Interface();
            }
            return _rivernodev1;
        }
    }
    public static WlInterface* RiverOutputV1
    {
        get
        {
            if (_riveroutputv1 == null)
            {
                _riveroutputv1 = CreateRiverOutputV1Interface();
            }
            return _riveroutputv1;
        }
    }
    public static WlInterface* RiverSeatV1
    {
        get
        {
            if (_riverseatv1 == null)
            {
                _riverseatv1 = CreateRiverSeatV1Interface();
            }
            return _riverseatv1;
        }
    }
    public static WlInterface* RiverPointerBindingV1
    {
        get
        {
            if (_riverpointerbindingv1 == null)
            {
                _riverpointerbindingv1 = CreateRiverPointerBindingV1Interface();
            }
            return _riverpointerbindingv1;
        }
    }

    public static IntPtr? GetRiverRuntimeInterface(string interfaceName)
    {
        return interfaceName switch
        {
            "river_window_manager_v1" => (IntPtr)RiverWindowManagerV1,
            "river_window_v1" => (IntPtr)RiverWindowV1,
            "river_decoration_v1" => (IntPtr)RiverDecorationV1,
            "river_shell_surface_v1" => (IntPtr)RiverShellSurfaceV1,
            "river_node_v1" => (IntPtr)RiverNodeV1,
            "river_output_v1" => (IntPtr)RiverOutputV1,
            "river_seat_v1" => (IntPtr)RiverSeatV1,
            "river_pointer_binding_v1" => (IntPtr)RiverPointerBindingV1,
            _ => null
        };
    }

    /// <summary>
    /// Interface: river_window_manager_v1
    /// Version: 3
    /// Requests: 6, Events: 9
    /// </summary>
    private static WlInterface* CreateRiverWindowManagerV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 6);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("stop"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("manage_finish"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("manage_dirty"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("render_finish"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("get_shell_surface"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("no"),
            Types = (WlInterface**)CreateTypesArray([RiverShellSurfaceV1, WlSurface])
        };

        // Event signatures
        var events = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 9);
        events[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("unavailable"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("finished"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("manage_start"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("render_start"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("session_locked"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("session_unlocked"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[6] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("window"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("n"),
            Types = (WlInterface**)CreateTypesArray([RiverWindowV1])
        };
        events[7] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("output"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("n"),
            Types = (WlInterface**)CreateTypesArray([RiverOutputV1])
        };
        events[8] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("seat"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("n"),
            Types = (WlInterface**)CreateTypesArray([RiverSeatV1])
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_window_manager_v1"),
            Version = 3,
            MethodCount = 6,
            Methods = requests,
            EventCount = 9,
            Events = events
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_window_v1
    /// Version: 3
    /// Requests: 23, Events: 16
    /// </summary>
    private static WlInterface* CreateRiverWindowV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 23);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("close"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("get_node"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("n"),
            Types = (WlInterface**)CreateTypesArray([RiverNodeV1])
        };
        requests[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("propose_dimensions"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("hide"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("show"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[6] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("use_csd"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[7] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("use_ssd"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[8] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_borders"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("uiuuuu"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[9] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_tiled"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("u"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        requests[10] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("get_decoration_above"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("no"),
            Types = (WlInterface**)CreateTypesArray([RiverDecorationV1, WlSurface])
        };
        requests[11] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("get_decoration_below"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("no"),
            Types = (WlInterface**)CreateTypesArray([RiverDecorationV1, WlSurface])
        };
        requests[12] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("inform_resize_start"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[13] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("inform_resize_end"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[14] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_capabilities"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("u"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        requests[15] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("inform_maximized"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[16] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("inform_unmaximized"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[17] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("inform_fullscreen"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[18] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("inform_not_fullscreen"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[19] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("fullscreen"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverOutputV1])
        };
        requests[20] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("exit_fullscreen"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[21] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_clip_box"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("iiii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[22] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_content_clip_box"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("iiii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };

        // Event signatures
        var events = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 16);
        events[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("closed"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("dimensions_hint"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("iiii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        events[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("dimensions"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        events[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("app_id"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("?s"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        events[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("title"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("?s"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        events[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("parent"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("?o"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        events[6] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("decoration_hint"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("u"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        events[7] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pointer_move_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverSeatV1])
        };
        events[8] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pointer_resize_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ou"),
            Types = (WlInterface**)CreateTypesArray([RiverSeatV1, (WlInterface*)IntPtr.Zero])
        };
        events[9] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("show_window_menu_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        events[10] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("maximize_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[11] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("unmaximize_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[12] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("fullscreen_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("?o"),
            Types = (WlInterface**)CreateTypesArray([RiverOutputV1])
        };
        events[13] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("exit_fullscreen_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[14] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("minimize_requested"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[15] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("unreliable_pid"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("i"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_window_v1"),
            Version = 3,
            MethodCount = 23,
            Methods = requests,
            EventCount = 16,
            Events = events
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_decoration_v1
    /// Version: 3
    /// Requests: 3, Events: 0
    /// </summary>
    private static WlInterface* CreateRiverDecorationV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 3);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_offset"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("sync_next_commit"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_decoration_v1"),
            Version = 3,
            MethodCount = 3,
            Methods = requests,
            EventCount = 0,
            Events = (WlMessage*)IntPtr.Zero
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_shell_surface_v1
    /// Version: 3
    /// Requests: 3, Events: 0
    /// </summary>
    private static WlInterface* CreateRiverShellSurfaceV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 3);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("get_node"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("n"),
            Types = (WlInterface**)CreateTypesArray([RiverNodeV1])
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("sync_next_commit"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_shell_surface_v1"),
            Version = 3,
            MethodCount = 3,
            Methods = requests,
            EventCount = 0,
            Events = (WlMessage*)IntPtr.Zero
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_node_v1
    /// Version: 3
    /// Requests: 6, Events: 0
    /// </summary>
    private static WlInterface* CreateRiverNodeV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 6);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_position"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("place_top"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("place_bottom"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("place_above"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        requests[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("place_below"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_node_v1"),
            Version = 3,
            MethodCount = 6,
            Methods = requests,
            EventCount = 0,
            Events = (WlMessage*)IntPtr.Zero
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_output_v1
    /// Version: 3
    /// Requests: 1, Events: 4
    /// </summary>
    private static WlInterface* CreateRiverOutputV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 1);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };

        // Event signatures
        var events = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 4);
        events[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("removed"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("wl_output"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("u"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        events[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("position"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        events[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("dimensions"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_output_v1"),
            Version = 3,
            MethodCount = 1,
            Methods = requests,
            EventCount = 4,
            Events = events
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_seat_v1
    /// Version: 3
    /// Requests: 9, Events: 9
    /// </summary>
    private static WlInterface* CreateRiverSeatV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 9);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("focus_window"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverWindowV1])
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("focus_shell_surface"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverShellSurfaceV1])
        };
        requests[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("clear_focus"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("op_start_pointer"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("op_end"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[6] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("get_pointer_binding"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("nuu"),
            Types = (WlInterface**)CreateTypesArray([RiverPointerBindingV1, (WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[7] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("set_xcursor_theme"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("su"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        requests[8] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pointer_warp"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };

        // Event signatures
        var events = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 9);
        events[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("removed"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("wl_seat"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("u"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero])
        };
        events[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pointer_enter"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverWindowV1])
        };
        events[3] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pointer_leave"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[4] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("window_interaction"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverWindowV1])
        };
        events[5] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("shell_surface_interaction"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("o"),
            Types = (WlInterface**)CreateTypesArray([RiverShellSurfaceV1])
        };
        events[6] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("op_delta"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };
        events[7] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("op_release"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[8] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pointer_position"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged("ii"),
            Types = (WlInterface**)CreateTypesArray([(WlInterface*)IntPtr.Zero, (WlInterface*)IntPtr.Zero])
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_seat_v1"),
            Version = 3,
            MethodCount = 9,
            Methods = requests,
            EventCount = 9,
            Events = events
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

    /// <summary>
    /// Interface: river_pointer_binding_v1
    /// Version: 3
    /// Requests: 3, Events: 2
    /// </summary>
    private static WlInterface* CreateRiverPointerBindingV1Interface()
    {
        // Request signatures
        var requests = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 3);
        requests[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("destroy"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("enable"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        requests[2] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("disable"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };

        // Event signatures
        var events = (WlMessage*)Marshal.AllocHGlobal(sizeof(WlMessage) * 2);
        events[0] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("pressed"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };
        events[1] = new WlMessage
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("released"),
            Signature = Utf8StringMarshaller.ConvertToUnmanaged(""),
            Types = (WlInterface**)IntPtr.Zero
        };

        var iface = new WlInterface
        {
            Name = Utf8StringMarshaller.ConvertToUnmanaged("river_pointer_binding_v1"),
            Version = 3,
            MethodCount = 3,
            Methods = requests,
            EventCount = 2,
            Events = events
        };

        var size = Marshal.SizeOf<WlInterface>();
        var ptr = (WlInterface*)Marshal.AllocHGlobal(size);
        Marshal.StructureToPtr(iface, (IntPtr)ptr, false);

        return ptr;
    }

}
