_default:
    @just Minimal

[working-directory: 'Minimal']
Minimal:
    dotnet run

[working-directory: 'LayerShell']
LayerShell:
    dotnet run

[working-directory: 'Taskbar']
Taskbar:
    dotnet run

[working-directory: 'TinyRwm']
TinyRwm:
    river -c "dotnet run"
