_default:
    @just Minimal

[working-directory: 'Minimal']
Minimal:
    dotnet run

[working-directory: 'LayerShell']
LayerShell:
    dotnet run

[working-directory: 'RiverWindowManager']
RiverWindowManager:
    WAYLAND_DISPLAY=wayland-2 dotnet run
