// <auto-generated>
// This file was generated from river-xkb-bindings-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-xkb-bindings-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_xkb_bindings_seat_v1
/// <para> xkb bindings seat </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/river-xkb-bindings-v1/#river_xkb_bindings_seat_v1</see>
/// </summary>
public sealed partial class RiverXkbBindingsSeatV1 : WaylandObject, IWaylandObjectFactory<RiverXkbBindingsSeatV1>
{
    public const string InterfaceName = "river_xkb_bindings_seat_v1";
    public static string _StaticInterfaceName => "river_xkb_bindings_seat_v1";
    public const int InterfaceVersion = 2;

    private bool disposed;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    public WlDisplay Display { get; private set; }

    public RiverXkbBindingsSeatV1(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    public delegate void AteUnboundKeyHandler();

    private AteUnboundKeyHandler? _onAteUnboundKey;

    /// <summary>
    ///An unbound key press event was eaten
    /// <para>
    ///
    ///An unbound key press event was eaten due to the ensure_next_key_eaten
    ///request.
    ///
    ///This event will be followed by a manage_start event after all other new
    ///state has been sent by the server.
    ///
    /// </para>
    /// </summary>
    public event AteUnboundKeyHandler? OnAteUnboundKey
    {
        add
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            _onAteUnboundKey += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onAteUnboundKey -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to river_xkb_bindings_seat_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (RiverXkbBindingsSeatV1)handle.Target!;
            var display = obj.Display;

            switch (opcode)
            {
                case 0: // ate_unbound_key
                    if (obj._onAteUnboundKey != null)
                    {
                        obj._onAteUnboundKey?.Invoke();
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    /// <summary>
    /// Destroy the object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the object and<br/>
    /// that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Ensure the next key press event is eaten
    /// <para>
    /// <br/>
    /// Ensure that the next non-modifier key press and corresponding release<br/>
    /// events for this seat are not sent to the currently focused surface.<br/>
    /// <br/>
    /// If the next non-modifier key press triggers a binding, the<br/>
    /// pressed/released events are sent to the river_xkb_binding_v1 object as<br/>
    /// usual.<br/>
    /// <br/>
    /// If the next non-modifier key press does not trigger a binding, the<br/>
    /// ate_unbound_key event is sent instead.<br/>
    /// <br/>
    /// Rationale: the window manager may wish to implement "chorded"<br/>
    /// keybindings where triggering a binding activates a "submap" with a<br/>
    /// different set of keybindings. Without a way to eat the next key<br/>
    /// press event, there is no good way for the window manager to know that it<br/>
    /// should error out and exit the submap when a key not bound in the submap<br/>
    /// is pressed.<br/>
    /// <br/>
    /// This request modifies window management state and may only be made as<br/>
    /// part of a manage sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void EnsureNextKeyEaten()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Cancel an ensure_next_key_eaten request
    /// <para>
    /// <br/>
    /// This requests cancels the effect of the latest ensure_next_key_eaten<br/>
    /// request if no key has been eaten due to the request yet. This request<br/>
    /// has no effect if a key has already been eaten or no<br/>
    /// ensure_next_key_eaten was made.<br/>
    /// <br/>
    /// Rationale: the window manager may wish cancel an uncompleted "chorded"<br/>
    /// keybinding after a timeout of a few seconds. Note that since this<br/>
    /// timeout use-case requires the window manager to trigger a manage sequence<br/>
    /// with the river_window_manager_v1.manage_dirty request it is possible that<br/>
    /// the ate_unbound_key key event may be sent before the window manager has<br/>
    /// a chance to make the cancel_ensure_next_key_eaten request.<br/>
    /// <br/>
    /// This request modifies window management state and may only be made as<br/>
    /// part of a manage sequence, see the river_window_manager_v1 description.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void CancelEnsureNextKeyEaten()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static RiverXkbBindingsSeatV1 Create(nint handle, WlDisplay? display = null)
    {
        return new RiverXkbBindingsSeatV1(handle, display);
    }
}
