// <auto-generated>
// This file was generated from river-xkb-bindings-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-xkb-bindings-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_xkb_bindings_v1
/// <para> xkbcommon bindings global interface </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/river-xkb-bindings-v1/#river_xkb_bindings_v1</see>
/// </summary>
public sealed partial class RiverXkbBindingsV1 : WaylandObject, IWaylandObjectFactory<RiverXkbBindingsV1>
{
    public const string InterfaceName = "river_xkb_bindings_v1";
    public static string _StaticInterfaceName => "river_xkb_bindings_v1";
    public const int InterfaceVersion = 2;

    public RiverXkbBindingsV1(IntPtr handle, WlDisplay? display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        ///
        /// </summary>
        ObjectAlreadyCreated = 0,
    }

    /// <summary>
    /// Destroy the river_xkb_bindings_v1 object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the<br/>
    /// river_xkb_bindings_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Define a new xkbcommon key binding
    /// <para>
    /// <br/>
    /// Define a key binding for the given seat in terms of an xkbcommon keysym<br/>
    /// and other configurable properties.<br/>
    /// <br/>
    /// The new key binding is not enabled until initial configuration is<br/>
    /// completed and the enable request is made during a manage sequence.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverXkbBindingV1 GetXkbBinding(RiverSeatV1 seat, uint keysym, uint modifiers)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[4];
        args[0].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);
        args[1].o = (WlObject*)IntPtr.Zero;
        args[2].u = keysym;
        args[3].u = modifiers;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverXkbBindingV1,
            (uint)WaylandInterfaces.RiverXkbBindingV1->Version,
            0,
            (nint)args
        );

        return new RiverXkbBindingV1(newProxy, Display);
    }

    /// <summary>
    /// Manage seat-specific state
    /// <para>
    /// <br/>
    /// Create an object to manage seat-specific xkb bindings state.<br/>
    /// <br/>
    /// It is a protocol error to make this request more than once for a given<br/>
    /// river_seat_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverXkbBindingsSeatV1 GetSeat(RiverSeatV1 seat)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverXkbBindingsSeatV1,
            (uint)WaylandInterfaces.RiverXkbBindingsSeatV1->Version,
            0,
            (nint)args
        );

        return new RiverXkbBindingsSeatV1(newProxy, Display);
    }

    public static RiverXkbBindingsV1 Create(nint handle, WlDisplay? display)
    {
        return new RiverXkbBindingsV1(handle, display);
    }
}
