// <auto-generated>
// This file was generated from river-layer-shell-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-layer-shell-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_layer_shell_v1
/// <para> river layer shell global interface </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/river-layer-shell-v1/#river_layer_shell_v1</see>
/// </summary>
public sealed partial class RiverLayerShellV1 : WaylandObject, IWaylandObjectFactory<RiverLayerShellV1>
{
    public const string InterfaceName = "river_layer_shell_v1";
    public static string _StaticInterfaceName => "river_layer_shell_v1";
    public const int InterfaceVersion = 1;

    public RiverLayerShellV1(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// the layer_shell_output/seat object was already created.
        /// </summary>
        ObjectAlreadyCreated = 0,
    }

    /// <summary>
    /// Destroy the river_layer_shell_v1 object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the<br/>
    /// river_layer_shell_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Get layer shell output state
    /// <para>
    /// <br/>
    /// It is a protocol error to make this request more than once for a given<br/>
    /// river_output_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverLayerShellOutputV1 GetOutput(RiverOutputV1 output)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(output?.Handle ?? IntPtr.Zero);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverLayerShellOutputV1,
            (uint)WaylandInterfaces.RiverLayerShellOutputV1->Version,
            0,
            (nint)args
        );

        return new RiverLayerShellOutputV1(newProxy, Display);
    }

    /// <summary>
    /// Get layer shell seat state
    /// <para>
    /// <br/>
    /// It is a protocol error to make this request more than once for a given<br/>
    /// river_seat_v1 object.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverLayerShellSeatV1 GetSeat(RiverSeatV1 seat)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverLayerShellSeatV1,
            (uint)WaylandInterfaces.RiverLayerShellSeatV1->Version,
            0,
            (nint)args
        );

        return new RiverLayerShellSeatV1(newProxy, Display);
    }

    public static RiverLayerShellV1 Create(nint handle, WlDisplay display)
    {
        return new RiverLayerShellV1(handle, display);
    }
}
