// <auto-generated>
// This file was generated from river-libinput-config-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-libinput-config-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_libinput_result_v1
/// <para> config application result </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/river-libinput-config-v1/#river_libinput_result_v1</see>
/// </summary>
public sealed partial class RiverLibinputResultV1 : WaylandObject, IWaylandObjectFactory<RiverLibinputResultV1>
{
    public const string InterfaceName = "river_libinput_result_v1";
    public static string _StaticInterfaceName => "river_libinput_result_v1";
    public const int InterfaceVersion = 1;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();

    public RiverLibinputResultV1(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    public delegate void SuccessHandler();

    private SuccessHandler? _onSuccess;

    /// <summary>
    ///Config success
    /// <para>
    ///
    ///The configuration was successfully applied to the device.
    ///
    /// </para>
    /// </summary>
    public event SuccessHandler? OnSuccess
    {
        add
        {
            CheckDisposed();
            _onSuccess += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onSuccess -= value;
        }
    }

    public delegate void UnsupportedHandler();

    private UnsupportedHandler? _onUnsupported;

    /// <summary>
    ///Config unsupported
    /// <para>
    ///
    ///The configuration is unsupported by the device and was ignored.
    ///
    /// </para>
    /// </summary>
    public event UnsupportedHandler? OnUnsupported
    {
        add
        {
            CheckDisposed();
            _onUnsupported += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onUnsupported -= value;
        }
    }

    public delegate void InvalidHandler();

    private InvalidHandler? _onInvalid;

    /// <summary>
    ///Config invalid
    /// <para>
    ///
    ///The configuration is invalid and was ignored.
    ///
    /// </para>
    /// </summary>
    public event InvalidHandler? OnInvalid
    {
        add
        {
            CheckDisposed();
            _onInvalid += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onInvalid -= value;
        }
    }

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to river_libinput_result_v1");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (RiverLibinputResultV1)handle.Target!;
            var display = obj.Display;

            switch (opcode)
            {
                case 0: // success
                    if (obj._onSuccess != null)
                    {
                        obj._onSuccess?.Invoke();
                    }
                    break;
                case 1: // unsupported
                    if (obj._onUnsupported != null)
                    {
                        obj._onUnsupported?.Invoke();
                    }
                    break;
                case 2: // invalid
                    if (obj._onInvalid != null)
                    {
                        obj._onInvalid?.Invoke();
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }
    public static RiverLibinputResultV1 Create(nint handle, WlDisplay display)
    {
        return new RiverLibinputResultV1(handle, display);
    }
    protected override void Dispose(bool disposing)
    {
        if (gcHandle.IsAllocated)
        {
            gcHandle.Free();
        }
        base.Dispose(disposing);
    }
}
