// <auto-generated>
// This file was generated from river-libinput-config-v1.xml
// Stability: River
// Link: https://wayland.app/protocols/river-libinput-config-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.River;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// river_libinput_accel_config_v1
/// <para> acceleration config </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/river-libinput-config-v1/#river_libinput_accel_config_v1</see>
/// </summary>
public sealed partial class RiverLibinputAccelConfigV1 : WaylandObject, IWaylandObjectFactory<RiverLibinputAccelConfigV1>
{
    public const string InterfaceName = "river_libinput_accel_config_v1";
    public static string _StaticInterfaceName => "river_libinput_accel_config_v1";
    public const int InterfaceVersion = 1;

    public RiverLibinputAccelConfigV1(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// invalid enum value or similar
        /// </summary>
        InvalidArg = 0,
    }

    /// <summary>  </summary>
    public enum AccelType : uint
    {
        /// <summary>
        ///
        /// </summary>
        Fallback = 0,
        /// <summary>
        ///
        /// </summary>
        Motion = 1,
        /// <summary>
        ///
        /// </summary>
        Scroll = 2,
    }

    /// <summary>
    /// Destroy the accel object
    /// <para>
    /// <br/>
    /// This request indicates that the client will no longer use the accel<br/>
    /// config object and that it may be safely destroyed.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Define custom acceleration function
    /// <para>
    /// <br/>
    /// Defines the acceleration function for a given movement type<br/>
    /// in an acceleration configuration with custom accel profile.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe RiverLibinputResultV1 SetPoints(uint type, byte[] step, byte[] points)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[4];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].u = type;
        args[2].a = WaylandMarshal.CreateWlArray(step);
        args[3].a = WaylandMarshal.CreateWlArray(points);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.RiverLibinputResultV1,
            (uint)WaylandInterfaces.RiverLibinputResultV1->Version,
            0,
            (nint)args
        );

        return new RiverLibinputResultV1(newProxy, Display);
    }

    public static RiverLibinputAccelConfigV1 Create(nint handle, WlDisplay display)
    {
        return new RiverLibinputAccelConfigV1(handle, display);
    }
}
