// <auto-generated>
// This file was generated from wlr-output-management-unstable-v1.xml
// Stability: Wlr
// Link: https://wayland.app/protocols/wlr-output-management-unstable-v1
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.Wlr;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// zwlr_output_configuration_head_v1
/// <para> head configuration </para>
/// <para> Version: 4 </para>
/// <see>https://wayland.app/protocols/wlr-output-management-unstable-v1/#zwlr_output_configuration_head_v1</see>
/// </summary>
public sealed partial class ZwlrOutputConfigurationHeadV1 : WaylandObject, IWaylandObjectFactory<ZwlrOutputConfigurationHeadV1>
{
    public const string InterfaceName = "zwlr_output_configuration_head_v1";
    public static string _StaticInterfaceName => "zwlr_output_configuration_head_v1";
    public const int InterfaceVersion = 4;

    private bool disposed;

    public ZwlrOutputConfigurationHeadV1(IntPtr handle)
    {
        Handle = handle;
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// property has already been set
        /// </summary>
        AlreadySet = 1,
        /// <summary>
        /// mode doesn't belong to head
        /// </summary>
        InvalidMode = 2,
        /// <summary>
        /// mode is invalid
        /// </summary>
        InvalidCustomMode = 3,
        /// <summary>
        /// transform value outside enum
        /// </summary>
        InvalidTransform = 4,
        /// <summary>
        /// scale negative or zero
        /// </summary>
        InvalidScale = 5,
        /// <summary>
        /// invalid enum value used in the set_adaptive_sync request
        /// </summary>
        InvalidAdaptiveSyncState = 6,
    }

    /// <summary>
    /// Set the mode
    /// <para>
    /// <br/>
    /// This request sets the head's mode.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetMode(ZwlrOutputModeV1 mode)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(mode?.Handle ?? IntPtr.Zero);

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set a custom mode
    /// <para>
    /// <br/>
    /// This request assigns a custom mode to the head. The size is given in<br/>
    /// physical hardware units of the output device. If set to zero, the<br/>
    /// refresh rate is unspecified.<br/>
    /// <br/>
    /// It is a protocol error to set both a mode and a custom mode.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetCustomMode(int width, int height, int refresh)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[3];
        args[0].i = width;
        args[1].i = height;
        args[2].i = refresh;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the position
    /// <para>
    /// <br/>
    /// This request sets the head's position in the global compositor space.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetPosition(int x, int y)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].i = x;
        args[1].i = y;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the transform
    /// <para>
    /// <br/>
    /// This request sets the head's transform.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetTransform(int transform)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].i = transform;

        const uint opcode = 3;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the scale
    /// <para>
    /// <br/>
    /// This request sets the head's scale.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetScale(WlFixed scale)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].f = scale;

        const uint opcode = 4;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Enable/disable adaptive sync
    /// <para>
    /// <br/>
    /// This request enables/disables adaptive sync. Adaptive sync is also<br/>
    /// known as Variable Refresh Rate or VRR.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetAdaptiveSync(uint state)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].u = state;

        const uint opcode = 5;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static ZwlrOutputConfigurationHeadV1 Create(nint handle, WlDisplay? display = null)
    {
        return new ZwlrOutputConfigurationHeadV1(handle);
    }
}
