[parallel]
download: wayland linux-dmabuf presentation-time tablet viewporter xdg-shell ext-workspace wlr-layer wlr-output wlr-foreign river

wayland:
    wget -qO "./Core/wayland.xml" https://gitlab.freedesktop.org/wayland/wayland/-/raw/main/protocol/wayland.xml

linux-dmabuf:
    wget -qO "./Stable/linux-dmabuf-v1.xml" https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/stable/linux-dmabuf/linux-dmabuf-v1.xml

presentation-time:
    wget -qO "./Stable/presentation-time.xml" https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/stable/presentation-time/presentation-time.xml

tablet:
    wget -qO "./Stable/tablet-v2.xml" https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/stable/tablet/tablet-v2.xml

viewporter:
    wget -qO "./Stable/viewporter.xml" https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/stable/viewporter/viewporter.xml

xdg-shell:
    wget -qO "./Stable/xdg-shell.xml" https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/stable/xdg-shell/xdg-shell.xml

ext-workspace:
    wget -qO "./Staging/ext-workspace-v1.xml" https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/staging/ext-workspace/ext-workspace-v1.xml

wlr-layer:
    wget -qO "./Wlr/wlr-layer-shell-unstable-v1.xml" https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-layer-shell-unstable-v1.xml

wlr-output:
    wget -qO "./Wlr/wlr-output-management-unstable-v1.xml" https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-output-management-unstable-v1.xml

wlr-foreign:
    wget -qO "./Wlr/wlr-foreign-toplevel-management-unstable-v1.xml" https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml

river:
    wget -qO "./River/river-window-management-v1.xml" https://codeberg.org/river/river/raw/branch/main/protocol/river-window-management-v1.xml