// <auto-generated>
// This file was generated from viewporter.xml
// Stability: Stable
// Link: https://wayland.app/protocols/viewporter
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.Stable;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wp_viewporter
/// <para> surface cropping and scaling </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/viewporter/#wp_viewporter</see>
/// </summary>
public sealed partial class WpViewporter : WaylandObject, IWaylandObjectFactory<WpViewporter>
{
    public const string InterfaceName = "wp_viewporter";
    public static string _StaticInterfaceName => "wp_viewporter";
    public const int InterfaceVersion = 1;

    public WpViewporter(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// the surface already has a viewport object associated
        /// </summary>
        ViewportExists = 0,
    }

    /// <summary>
    /// Unbind from the cropping and scaling interface
    /// <para>
    /// <br/>
    /// Informs the server that the client will not be using this<br/>
    /// protocol object anymore. This does not affect any other objects,<br/>
    /// wp_viewport objects included.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Extend surface interface for crop and scale
    /// <para>
    /// <br/>
    /// Instantiate an interface extension for the given wl_surface to<br/>
    /// crop and scale its content. If the given wl_surface already has<br/>
    /// a wp_viewport object associated, the viewport_exists<br/>
    /// protocol error is raised.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WpViewport GetViewport(WlSurface surface)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(surface?.Handle ?? IntPtr.Zero);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WpViewport,
            (uint)WaylandInterfaces.WpViewport->Version,
            0,
            (nint)args
        );

        return new WpViewport(newProxy, Display);
    }

    public static WpViewporter Create(nint handle, WlDisplay display)
    {
        return new WpViewporter(handle, display);
    }
}
