// <auto-generated>
// This file was generated from viewporter.xml
// Stability: Stable
// Link: https://wayland.app/protocols/viewporter
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet.Stable;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wp_viewport
/// <para> crop and scale interface to a wl_surface </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/viewporter/#wp_viewport</see>
/// </summary>
public sealed partial class WpViewport : WaylandObject, IWaylandObjectFactory<WpViewport>
{
    public const string InterfaceName = "wp_viewport";
    public static string _StaticInterfaceName => "wp_viewport";
    public const int InterfaceVersion = 1;

    public WpViewport(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// negative or zero values in width or height
        /// </summary>
        BadValue = 0,
        /// <summary>
        /// destination size is not integer
        /// </summary>
        BadSize = 1,
        /// <summary>
        /// source rectangle extends outside of the content area
        /// </summary>
        OutOfBuffer = 2,
        /// <summary>
        /// the wl_surface was destroyed
        /// </summary>
        NoSurface = 3,
    }

    /// <summary>
    /// Remove scaling and cropping from the surface
    /// <para>
    /// <br/>
    /// The associated wl_surface's crop and scale state is removed.<br/>
    /// The change is applied on the next wl_surface.commit.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the source rectangle for cropping
    /// <para>
    /// <br/>
    /// Set the source rectangle of the associated wl_surface. See<br/>
    /// wp_viewport for the description, and relation to the wl_buffer<br/>
    /// size.<br/>
    /// <br/>
    /// If all of x, y, width and height are -1.0, the source rectangle is<br/>
    /// unset instead. Any other set of values where width or height are zero<br/>
    /// or negative, or x or y are negative, raise the bad_value protocol<br/>
    /// error.<br/>
    /// <br/>
    /// The crop and scale state is double-buffered, see wl_surface.commit.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetSource(WlFixed x, WlFixed y, WlFixed width, WlFixed height)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[4];
        args[0].f = x;
        args[1].f = y;
        args[2].f = width;
        args[3].f = height;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Set the surface size for scaling
    /// <para>
    /// <br/>
    /// Set the destination size of the associated wl_surface. See<br/>
    /// wp_viewport for the description, and relation to the wl_buffer<br/>
    /// size.<br/>
    /// <br/>
    /// If width is -1 and height is -1, the destination size is unset<br/>
    /// instead. Any other pair of values for width and height that<br/>
    /// contains zero or negative values raises the bad_value protocol<br/>
    /// error.<br/>
    /// <br/>
    /// The crop and scale state is double-buffered, see wl_surface.commit.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void SetDestination(int width, int height)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].i = width;
        args[1].i = height;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static WpViewport Create(nint handle, WlDisplay display)
    {
        return new WpViewport(handle, display);
    }
}
