// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_compositor
/// <para> the compositor singleton </para>
/// <para> Version: 6 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_compositor</see>
/// </summary>
public sealed partial class WlCompositor : WaylandObject, IWaylandObjectFactory<WlCompositor>
{
    public const string InterfaceName = "wl_compositor";
    public const int InterfaceVersion = 6;


    #region GenerateConstructor

    public WlCompositor(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateRequests

    /// <summary>
    /// Create new surface
    /// <para>
    /// <br/>
    /// Ask the compositor to create a new surface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlSurface CreateSurface()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlSurface,
            (uint)WaylandInterfaces.WlSurface->Version,
            0,
            (nint)args
        );

        return new WlSurface(newProxy, Display);
    }

    /// <summary>
    /// Create new region
    /// <para>
    /// <br/>
    /// Ask the compositor to create a new region.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlRegion CreateRegion()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlRegion,
            (uint)WaylandInterfaces.WlRegion->Version,
            0,
            (nint)args
        );

        return new WlRegion(newProxy, Display);
    }


    #endregion // GenerateRequests

    public static WlCompositor Create(nint handle, WlDisplay display)
    {
        return new WlCompositor(handle, display);
    }
}
