// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_data_device_manager
/// <para> data transfer interface </para>
/// <para> Version: 3 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_data_device_manager</see>
/// </summary>
public sealed partial class WlDataDeviceManager : WaylandObject, IWaylandObjectFactory<WlDataDeviceManager>
{
    public const string InterfaceName = "wl_data_device_manager";
    public const int InterfaceVersion = 3;


    #region GenerateConstructor

    public WlDataDeviceManager(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateEnums

    /// <summary> drag and drop actions </summary>
    [Flags]
    public enum DndActionFlag : uint
    {
        /// <summary>
        /// no action
        /// </summary>
        None = 0,
        /// <summary>
        /// copy action
        /// </summary>
        Copy = 1,
        /// <summary>
        /// move action
        /// </summary>
        Move = 2,
        /// <summary>
        /// ask action
        /// </summary>
        Ask = 4,
    }


    #endregion // GenerateEnums


    #region GenerateRequests

    /// <summary>
    /// Create a new data source
    /// <para>
    /// <br/>
    /// Create a new data source.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlDataSource CreateDataSource()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlDataSource,
            (uint)WaylandInterfaces.WlDataSource->Version,
            0,
            (nint)args
        );

        return new WlDataSource(newProxy, Display);
    }

    /// <summary>
    /// Create a new data device
    /// <para>
    /// <br/>
    /// Create a new data device for a given seat.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlDataDevice GetDataDevice(WlSeat seat)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlDataDevice,
            (uint)WaylandInterfaces.WlDataDevice->Version,
            0,
            (nint)args
        );

        return new WlDataDevice(newProxy, Display);
    }


    #endregion // GenerateRequests

    public static WlDataDeviceManager Create(nint handle, WlDisplay display)
    {
        return new WlDataDeviceManager(handle, display);
    }
}
