// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Staging;
using WaylandDotnet.Unstable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_data_device_manager
/// <para> data transfer interface </para>
/// <para> Version: 4 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_data_device_manager</see>
/// </summary>
public sealed partial class WlDataDeviceManager : WaylandObject, IWaylandObjectFactory<WlDataDeviceManager>
{
    public const string InterfaceName = "wl_data_device_manager";
    public static string _StaticInterfaceName => "wl_data_device_manager";
    public const int InterfaceVersion = 4;

    private bool disposed;

    public WlDisplay Display { get; private set; }

    public WlDataDeviceManager(IntPtr handle, WlDisplay display)
    {
        Display = display;
        Handle = handle;
    }
    /// <summary> drag and drop actions </summary>
    [Flags]
    public enum DndActionFlag : uint
    {
        /// <summary>
        /// no action
        /// </summary>
        None = 0,
        /// <summary>
        /// copy action
        /// </summary>
        Copy = 1,
        /// <summary>
        /// move action
        /// </summary>
        Move = 2,
        /// <summary>
        /// ask action
        /// </summary>
        Ask = 4,
    }

    /// <summary>
    /// Create a new data source
    /// <para>
    /// <br/>
    /// Create a new data source.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlDataSource CreateDataSource()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)IntPtr.Zero;

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlDataSource,
            (uint)WaylandInterfaces.WlDataSource->Version,
            0,
            (nint)args
        );

        return new WlDataSource(newProxy, Display);
    }

    /// <summary>
    /// Create a new data device
    /// <para>
    /// <br/>
    /// Create a new data device for a given seat.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlDataDevice GetDataDevice(WlSeat seat)
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(seat?.Handle ?? IntPtr.Zero);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlDataDevice,
            (uint)WaylandInterfaces.WlDataDevice->Version,
            0,
            (nint)args
        );

        return new WlDataDevice(newProxy, Display);
    }

    /// <summary>
    /// Destroy wl_data_device_manager
    /// <para>
    /// <br/>
    /// This request destroys the wl_data_device_manager. This has no effect on any other<br/>
    /// objects.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Release()
    {
        ObjectDisposedException.ThrowIf(disposed, this);

        var args = stackalloc WlArgument[0];

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static WlDataDeviceManager Create(nint handle, WlDisplay? display = null)
    {
        return new WlDataDeviceManager(handle, display);
    }
}
