// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_fixes
/// <para> wayland protocol fixes </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_fixes</see>
/// </summary>
public sealed partial class WlFixes : WaylandObject, IWaylandObjectFactory<WlFixes>
{
    public const string InterfaceName = "wl_fixes";
    public static string _StaticInterfaceName => "wl_fixes";
    public const int InterfaceVersion = 1;

    public WlFixes(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>
    /// Destroys this object
    /// <para>
    /// destroy<br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Destroy a wl_registry
    /// <para>
    /// <br/>
    /// This request destroys a wl_registry object.<br/>
    /// <br/>
    /// The client should no longer use the wl_registry after making this<br/>
    /// request.<br/>
    /// <br/>
    /// The compositor will emit a wl_display.delete_id event with the object ID<br/>
    /// of the registry and will no longer emit any events on the registry. The<br/>
    /// client should re-use the object ID once it receives the<br/>
    /// wl_display.delete_id event.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void DestroyRegistry(WlRegistry registry)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].o = (WlObject*)(registry?.Handle ?? IntPtr.Zero);

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static WlFixes Create(nint handle, WlDisplay display)
    {
        return new WlFixes(handle, display);
    }
}
