// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_output
/// <para> compositor output region </para>
/// <para> Version: 4 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_output</see>
/// </summary>
public sealed partial class WlOutput : WaylandObject, IWaylandObjectFactory<WlOutput>
{
    public const string InterfaceName = "wl_output";
    public const int InterfaceVersion = 4;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();


    #region GenerateConstructor

    public WlOutput(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateEnums

    /// <summary> subpixel geometry information </summary>
    public enum Subpixel : uint
    {
        /// <summary>
        /// unknown geometry
        /// </summary>
        Unknown = 0,
        /// <summary>
        /// no geometry
        /// </summary>
        None = 1,
        /// <summary>
        /// horizontal RGB
        /// </summary>
        HorizontalRgb = 2,
        /// <summary>
        /// horizontal BGR
        /// </summary>
        HorizontalBgr = 3,
        /// <summary>
        /// vertical RGB
        /// </summary>
        VerticalRgb = 4,
        /// <summary>
        /// vertical BGR
        /// </summary>
        VerticalBgr = 5,
    }

    /// <summary> transformation applied to buffer contents </summary>
    public enum Transform : uint
    {
        /// <summary>
        /// no transform
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 90 degrees counter-clockwise
        /// </summary>
        _90 = 1,
        /// <summary>
        /// 180 degrees counter-clockwise
        /// </summary>
        _180 = 2,
        /// <summary>
        /// 270 degrees counter-clockwise
        /// </summary>
        _270 = 3,
        /// <summary>
        /// 180 degree flip around a vertical axis
        /// </summary>
        Flipped = 4,
        /// <summary>
        /// flip and rotate 90 degrees counter-clockwise
        /// </summary>
        Flipped90 = 5,
        /// <summary>
        /// flip and rotate 180 degrees counter-clockwise
        /// </summary>
        Flipped180 = 6,
        /// <summary>
        /// flip and rotate 270 degrees counter-clockwise
        /// </summary>
        Flipped270 = 7,
    }

    /// <summary> mode information </summary>
    [Flags]
    public enum ModeFlag : uint
    {
        /// <summary>
        /// indicates this is the current mode
        /// </summary>
        Current = 0x1,
        /// <summary>
        /// indicates this is the preferred mode
        /// </summary>
        Preferred = 0x2,
    }


    #endregion // GenerateEnums


    #region GenerateEventDelegates

    public delegate void GeometryHandler(int x, int y, int physicalWidth, int physicalHeight, int subpixel, string make, string model, int transform);

    private GeometryHandler? _onGeometry;

    public event GeometryHandler? OnGeometry
    {
        add
        {
            CheckDisposed();
            _onGeometry += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onGeometry -= value;
        }
    }

    public delegate void ModeHandler(uint flags, int width, int height, int refresh);

    private ModeHandler? _onMode;

    public event ModeHandler? OnMode
    {
        add
        {
            CheckDisposed();
            _onMode += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onMode -= value;
        }
    }

    public delegate void DoneHandler();

    private DoneHandler? _onDone;

    public event DoneHandler? OnDone
    {
        add
        {
            CheckDisposed();
            _onDone += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onDone -= value;
        }
    }

    public delegate void ScaleHandler(int factor);

    private ScaleHandler? _onScale;

    public event ScaleHandler? OnScale
    {
        add
        {
            CheckDisposed();
            _onScale += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onScale -= value;
        }
    }

    public delegate void NameHandler(string name);

    private NameHandler? _onName;

    public event NameHandler? OnName
    {
        add
        {
            CheckDisposed();
            _onName += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onName -= value;
        }
    }

    public delegate void DescriptionHandler(string description);

    private DescriptionHandler? _onDescription;

    public event DescriptionHandler? OnDescription
    {
        add
        {
            CheckDisposed();
            _onDescription += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onDescription -= value;
        }
    }


    #endregion // GenerateEventDelegates


    #region GenerateEvents

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to wl_output");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (WlOutput)handle.Target!;
            var display = obj.Display;

            switch (opcode)
            {
                case 0: // geometry
                    if (obj._onGeometry != null)
                    {
                        var _x = args[0].i;
                        var _y = args[1].i;
                        var _physicalWidth = args[2].i;
                        var _physicalHeight = args[3].i;
                        var _subpixel = args[4].i;
                        var _make = Utf8StringMarshaller.ConvertToManaged(args[5].s);
                        var _model = Utf8StringMarshaller.ConvertToManaged(args[6].s);
                        var _transform = args[7].i;
                        obj._onGeometry?.Invoke(_x, _y, _physicalWidth, _physicalHeight, _subpixel, _make, _model, _transform);
                    }
                    break;
                case 1: // mode
                    if (obj._onMode != null)
                    {
                        var _flags = args[0].u;
                        var _width = args[1].i;
                        var _height = args[2].i;
                        var _refresh = args[3].i;
                        obj._onMode?.Invoke(_flags, _width, _height, _refresh);
                    }
                    break;
                case 2: // done
                    if (obj._onDone != null)
                    {
                        obj._onDone?.Invoke();
                    }
                    break;
                case 3: // scale
                    if (obj._onScale != null)
                    {
                        var _factor = args[0].i;
                        obj._onScale?.Invoke(_factor);
                    }
                    break;
                case 4: // name
                    if (obj._onName != null)
                    {
                        var _name = Utf8StringMarshaller.ConvertToManaged(args[0].s);
                        obj._onName?.Invoke(_name);
                    }
                    break;
                case 5: // description
                    if (obj._onDescription != null)
                    {
                        var _description = Utf8StringMarshaller.ConvertToManaged(args[0].s);
                        obj._onDescription?.Invoke(_description);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }

    #endregion // GenerateEvents


    #region GenerateRequests

    /// <summary>
    /// Release the output object
    /// <para>
    /// <br/>
    /// Using this request a client can tell the server that it is not going to<br/>
    /// use the output object anymore.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Release()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }


    #endregion // GenerateRequests

    public static WlOutput Create(nint handle, WlDisplay display)
    {
        return new WlOutput(handle, display);
    }

    #region GenerateDisposeOverride

    protected override void Dispose(bool disposing)
    {
        if (gcHandle.IsAllocated)
        {
            gcHandle.Free();
        }
        base.Dispose(disposing);
    }

    #endregion // GenerateDisposeOverride

}
