// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_region
/// <para> region interface </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_region</see>
/// </summary>
public sealed partial class WlRegion : WaylandObject, IWaylandObjectFactory<WlRegion>
{
    public const string InterfaceName = "wl_region";
    public static string _StaticInterfaceName => "wl_region";
    public const int InterfaceVersion = 1;

    public WlRegion(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }
    /// <summary>
    /// Destroy region
    /// <para>
    /// <br/>
    /// Destroy the region.  This will invalidate the object ID.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Add rectangle to region
    /// <para>
    /// <br/>
    /// Add the specified rectangle to the region.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Add(int x, int y, int width, int height)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[4];
        args[0].i = x;
        args[1].i = y;
        args[2].i = width;
        args[3].i = height;

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Subtract rectangle from region
    /// <para>
    /// <br/>
    /// Subtract the specified rectangle from the region.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Subtract(int x, int y, int width, int height)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[4];
        args[0].i = x;
        args[1].i = y;
        args[2].i = width;
        args[3].i = height;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    public static WlRegion Create(nint handle, WlDisplay display)
    {
        return new WlRegion(handle, display);
    }
}
