// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_shell
/// <para> create desktop-style surfaces </para>
/// <para> Version: 1 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_shell</see>
/// </summary>
public sealed partial class WlShell : WaylandObject, IWaylandObjectFactory<WlShell>
{
    public const string InterfaceName = "wl_shell";
    public const int InterfaceVersion = 1;


    #region GenerateConstructor

    public WlShell(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateEnums

    /// <summary>  </summary>
    public enum Error : uint
    {
        /// <summary>
        /// given wl_surface has another role
        /// </summary>
        Role = 0,
    }


    #endregion // GenerateEnums


    #region GenerateRequests

    /// <summary>
    /// Create a shell surface from a surface
    /// <para>
    /// <br/>
    /// Create a shell surface for an existing surface. This gives<br/>
    /// the wl_surface the role of a shell surface. If the wl_surface<br/>
    /// already has another role, it raises a protocol error.<br/>
    /// <br/>
    /// Only one shell surface can be associated with a given surface.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlShellSurface GetShellSurface(WlSurface surface)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[2];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].o = (WlObject*)(surface?.Handle ?? IntPtr.Zero);

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlShellSurface,
            (uint)WaylandInterfaces.WlShellSurface->Version,
            0,
            (nint)args
        );

        return new WlShellSurface(newProxy, Display);
    }


    #endregion // GenerateRequests

    public static WlShell Create(nint handle, WlDisplay display)
    {
        return new WlShell(handle, display);
    }
}
