// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_shm_pool
/// <para> a shared memory pool </para>
/// <para> Version: 2 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_shm_pool</see>
/// </summary>
public sealed partial class WlShmPool : WaylandObject, IWaylandObjectFactory<WlShmPool>
{
    public const string InterfaceName = "wl_shm_pool";
    public static string _StaticInterfaceName => "wl_shm_pool";
    public const int InterfaceVersion = 2;


    #region GenerateConstructor

    public WlShmPool(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateRequests

    /// <summary>
    /// Create a buffer from the pool
    /// <para>
    /// <br/>
    /// Create a wl_buffer object from the pool.<br/>
    /// <br/>
    /// The buffer is created offset bytes into the pool and has<br/>
    /// width and height as specified.  The stride argument specifies<br/>
    /// the number of bytes from the beginning of one row to the beginning<br/>
    /// of the next.  The format is the pixel format of the buffer and<br/>
    /// must be one of those advertised through the wl_shm.format event.<br/>
    /// <br/>
    /// A buffer will keep a reference to the pool it was created from<br/>
    /// so it is valid to destroy the pool immediately after creating<br/>
    /// a buffer from it.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe WlBuffer CreateBuffer(int offset, int width, int height, int stride, uint format)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[6];
        args[0].o = (WlObject*)IntPtr.Zero;
        args[1].i = offset;
        args[2].i = width;
        args[3].i = height;
        args[4].i = stride;
        args[5].u = format;

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            WaylandInterfaces.WlBuffer,
            (uint)WaylandInterfaces.WlBuffer->Version,
            0,
            (nint)args
        );

        return new WlBuffer(newProxy, Display);
    }

    /// <summary>
    /// Destroy the pool
    /// <para>
    /// <br/>
    /// Destroy the shared memory pool.<br/>
    /// <br/>
    /// The mmapped memory will be released when all<br/>
    /// buffers that have been created from this pool<br/>
    /// are gone.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Destroy()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 1;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }

    /// <summary>
    /// Change the size of the pool mapping
    /// <para>
    /// <br/>
    /// This request will cause the server to remap the backing memory<br/>
    /// for the pool from the file descriptor passed when the pool was<br/>
    /// created, but using the new size.  This request can only be<br/>
    /// used to make the pool bigger.<br/>
    /// <br/>
    /// This request only changes the amount of bytes that are mmapped<br/>
    /// by the server and does not touch the file corresponding to the<br/>
    /// file descriptor passed at creation time. It is the client's<br/>
    /// responsibility to ensure that the file is at least as big as<br/>
    /// the new pool size.<br/>
    /// <br/>
    /// </para>
    /// </summary>
    public unsafe void Resize(int size)
    {
        CheckDisposed();

        var args = stackalloc WlArgument[1];
        args[0].i = size;

        const uint opcode = 2;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }


    #endregion // GenerateRequests

    public static WlShmPool Create(nint handle, WlDisplay display)
    {
        return new WlShmPool(handle, display);
    }
}
