// <auto-generated>
// This file was generated from wayland.xml
// Stability: Core
// Link: https://wayland.app/protocols/wayland
// </auto-generated>

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS0108
#pragma warning disable CS8604

namespace WaylandDotnet;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Text;
using WaylandDotnet;
using WaylandDotnet.Internal;
using WaylandDotnet.Stable;
using WaylandDotnet.Wlr;

/// <summary>
/// wl_touch
/// <para> touchscreen input device </para>
/// <para> Version: 10 </para>
/// <see>https://wayland.app/protocols/wayland/#wl_touch</see>
/// </summary>
public sealed partial class WlTouch : WaylandObject, IWaylandObjectFactory<WlTouch>
{
    public const string InterfaceName = "wl_touch";
    public const int InterfaceVersion = 10;

    private GCHandle gcHandle;
    private bool dispatcherRegistered = false;
    private readonly object dispatcherLock = new object();


    #region GenerateConstructor

    public WlTouch(IntPtr handle, WlDisplay display) : base(handle, display, InterfaceName, InterfaceVersion)
    {
    }

    #endregion // GenerateConstructor


    #region GenerateEventDelegates

    public delegate void DownHandler(uint serial, uint time, WlSurface surface, int id, WlFixed x, WlFixed y);

    private DownHandler? _onDown;

    public event DownHandler? OnDown
    {
        add
        {
            CheckDisposed();
            _onDown += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onDown -= value;
        }
    }

    public delegate void UpHandler(uint serial, uint time, int id);

    private UpHandler? _onUp;

    public event UpHandler? OnUp
    {
        add
        {
            CheckDisposed();
            _onUp += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onUp -= value;
        }
    }

    public delegate void MotionHandler(uint time, int id, WlFixed x, WlFixed y);

    private MotionHandler? _onMotion;

    public event MotionHandler? OnMotion
    {
        add
        {
            CheckDisposed();
            _onMotion += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onMotion -= value;
        }
    }

    public delegate void FrameHandler();

    private FrameHandler? _onFrame;

    public event FrameHandler? OnFrame
    {
        add
        {
            CheckDisposed();
            _onFrame += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onFrame -= value;
        }
    }

    public delegate void CancelHandler();

    private CancelHandler? _onCancel;

    public event CancelHandler? OnCancel
    {
        add
        {
            CheckDisposed();
            _onCancel += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onCancel -= value;
        }
    }

    public delegate void ShapeHandler(int id, WlFixed major, WlFixed minor);

    private ShapeHandler? _onShape;

    public event ShapeHandler? OnShape
    {
        add
        {
            CheckDisposed();
            _onShape += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onShape -= value;
        }
    }

    public delegate void OrientationHandler(int id, WlFixed orientation);

    private OrientationHandler? _onOrientation;

    public event OrientationHandler? OnOrientation
    {
        add
        {
            CheckDisposed();
            _onOrientation += value;
            EnsureDispatcherRegistered();
        }

        remove
        {
            _onOrientation -= value;
        }
    }


    #endregion // GenerateEventDelegates


    #region GenerateEvents

    private unsafe void EnsureDispatcherRegistered()
    {
        lock (dispatcherLock)
        {
            if (dispatcherRegistered)
            {
                return;
            }

            // Allocate GCHandle to keep this object alive
            gcHandle = GCHandle.Alloc(this, GCHandleType.Normal);

            // Register the dispatcher with the Wayland proxy
            var dataPtr = GCHandle.ToIntPtr(gcHandle);
            var result = WaylandNative.ProxyAddDispatcher(Handle, &DispatchEvent, dataPtr, IntPtr.Zero);
            if (result != 0)
            {
                gcHandle.Free();
                throw new InvalidOperationException("Failed to add dispatcher to wl_touch");
            }

            dispatcherRegistered = true;
        }
    }

    [UnmanagedCallersOnly]
    private static unsafe int DispatchEvent(IntPtr userData, IntPtr target, uint opcode, WlMessage* message, WlArgument* args)
    {
        try
        {
            var handle = GCHandle.FromIntPtr(userData);
            var obj = (WlTouch)handle.Target!;
            var display = obj.Display;

            switch (opcode)
            {
                case 0: // down
                    if (obj._onDown != null)
                    {
                        var _serial = args[0].u;
                        var _time = args[1].u;
                        WlSurface? _surface = null;
                        if (args[2].o == (WlObject*)IntPtr.Zero) throw new InvalidOperationException("Received null object for non-nullable argument 'surface'");
                        _surface = new WlSurface((IntPtr)args[2].o, obj.Display);
                        var _id = args[3].i;
                        var _x = args[4].f;
                        var _y = args[5].f;
                        obj._onDown?.Invoke(_serial, _time, _surface, _id, _x, _y);
                    }
                    break;
                case 1: // up
                    if (obj._onUp != null)
                    {
                        var _serial = args[0].u;
                        var _time = args[1].u;
                        var _id = args[2].i;
                        obj._onUp?.Invoke(_serial, _time, _id);
                    }
                    break;
                case 2: // motion
                    if (obj._onMotion != null)
                    {
                        var _time = args[0].u;
                        var _id = args[1].i;
                        var _x = args[2].f;
                        var _y = args[3].f;
                        obj._onMotion?.Invoke(_time, _id, _x, _y);
                    }
                    break;
                case 3: // frame
                    if (obj._onFrame != null)
                    {
                        obj._onFrame?.Invoke();
                    }
                    break;
                case 4: // cancel
                    if (obj._onCancel != null)
                    {
                        obj._onCancel?.Invoke();
                    }
                    break;
                case 5: // shape
                    if (obj._onShape != null)
                    {
                        var _id = args[0].i;
                        var _major = args[1].f;
                        var _minor = args[2].f;
                        obj._onShape?.Invoke(_id, _major, _minor);
                    }
                    break;
                case 6: // orientation
                    if (obj._onOrientation != null)
                    {
                        var _id = args[0].i;
                        var _orientation = args[1].f;
                        obj._onOrientation?.Invoke(_id, _orientation);
                    }
                    break;
                default:
                    return -1;
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error in event dispatcher: {ex}");
            return -1;
        }
    }

    #endregion // GenerateEvents


    #region GenerateRequests

    /// <summary>
    /// Release the touch object
    /// <para>
    /// release<br/>
    /// </para>
    /// </summary>
    public unsafe void Release()
    {
        CheckDisposed();

        var args = stackalloc WlArgument[0];

        const uint opcode = 0;

        var newProxy = WaylandNative.ProxyMarshalArrayFlags(
            Handle,
            opcode,
            (WlInterface*)IntPtr.Zero,
            0,
            0,
            (nint)args
        );
    }


    #endregion // GenerateRequests

    public static WlTouch Create(nint handle, WlDisplay display)
    {
        return new WlTouch(handle, display);
    }

    #region GenerateDisposeOverride

    protected override void Dispose(bool disposing)
    {
        if (gcHandle.IsAllocated)
        {
            gcHandle.Free();
        }
        base.Dispose(disposing);
    }

    #endregion // GenerateDisposeOverride

}
